{% set unix_version = "5.26.3" %}
{% set win_version = unix_version + ".1" %}

package:
  name: perl
  version: {{ unix_version }}  # [not win]
  version: {{ win_version }}   # [win]

source:
  url: http://www.cpan.org/src/5.0/perl-{{ unix_version }}.tar.gz                                                 # [unix]
  url: http://strawberryperl.com/download/{{ win_version }}/strawberry-perl-{{ win_version }}-64bit-portable.zip  # [win64]
  url: http://strawberryperl.com/download/{{ win_version }}/strawberry-perl-{{ win_version }}-32bit-portable.zip  # [win32]
  sha256: b75ae40de8292fa53021b35eb3552fcaf65d7891ce4c5b6668d665cb0233c493                                        # [unix]
  # sha1 hashes published at: http://strawberryperl.com/releases.html
  sha1: 04dcda8a5e4cdd00414a18676240739e51773dbf                                                                  # [win64]
  sha1: 4ca969d273c823cf812b302dc157a7549cf0aaa1                                                                  # [win32]

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}   # [unix]
    - make                  # [unix]

test:
  # downstreams:
  #   - git
  #   - automake
  commands:
    - perl --help

about:
  home: http://www.perl.org/
  license: Perl Artistic
  license_family: Other
  summary: "The Perl programming language interpreter."
  description: |
    Perl 5 is a highly capable, feature-rich programming language with over 29
    years of development. Perl 5 runs on over 100 platforms from portables to
    mainframes and is suitable for both rapid prototyping and large scale
    development projects.
  doc_url: https://www.perl.org/docs.html
  dev_url: https://perl5.git.perl.org/perl.git

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - mingwandroid
